[package]
name = "siskin"
version = "0.1.0"
edition = "2021"

default-run = "bytecode"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.18.0"
enum-as-inner = "0.6.0"
